add 15
blaackpanter/java-shareit pull request #3
Opened 2024-05-10 13:15 UTC by blaackpanter

2024-05-12 10:45 UTC, db-exp requested changes

2024-05-12 10:45 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
давай на публичные методы с записью добавить Transactional без readOnly на запись/чтение и на на публичные методы с чтением Transactional (readOnly=true)

2024-05-12 10:45 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private String description;
можно и size добавить

2024-05-12 10:45 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +public class ItemRequestServiceImpl implements ItemRequestService {
давай на публичные методы с записью добавить Transactional без readOnly на запись/чтение и на на публичные методы с чтением Transactional (readOnly=true)

2024-05-12 11:49 UTC, blaackpanter commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private String description;
Поправила

2024-05-12 11:49 UTC, blaackpanter commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +public class ItemRequestServiceImpl implements ItemRequestService {
Поправила

2024-05-12 11:49 UTC, blaackpanter commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
Поправила

2024-05-13 09:12 UTC, db-exp approved these changes

2024-05-13 09:16 UTC, merged